### ISSUE TITLE
ArgumentError: The provided regular expression is using multiline anchors

### ISSUE THREAD

**Issue by curbsaleem** [siong1987/mongoid_shortener#6]
MongoidShortener.generate("http://google.com")
ArgumentError: The provided regular expression is using multiline anchors (^ or $), which may present a security risk. Did you mean to use \A and \z, or forgot to add the :multiline => true option?

**Comment by sssionggg** [comment]
@curbsaleem i am not longer using this.  feel free to fix it.  i believe that this is a new security issue that will only be raised in a newer version of ruby.
